// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/ai_service.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AICallRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prompt        string                 `protobuf:"bytes,1,opt,name=prompt,proto3" json:"prompt,omitempty"`
	Model         string                 `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
	MaxTokens     int32                  `protobuf:"varint,3,opt,name=max_tokens,json=maxTokens,proto3" json:"max_tokens,omitempty"`
	Temperature   float32                `protobuf:"fixed32,4,opt,name=temperature,proto3" json:"temperature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AICallRequest) Reset() {
	*x = AICallRequest{}
	mi := &file_proto_ai_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AICallRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AICallRequest) ProtoMessage() {}

func (x *AICallRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ai_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AICallRequest.ProtoReflect.Descriptor instead.
func (*AICallRequest) Descriptor() ([]byte, []int) {
	return file_proto_ai_service_proto_rawDescGZIP(), []int{0}
}

func (x *AICallRequest) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *AICallRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *AICallRequest) GetMaxTokens() int32 {
	if x != nil {
		return x.MaxTokens
	}
	return 0
}

func (x *AICallRequest) GetTemperature() float32 {
	if x != nil {
		return x.Temperature
	}
	return 0
}

type AICallResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        string                 `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	Model         string                 `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
	TokenCount    int32                  `protobuf:"varint,3,opt,name=token_count,json=tokenCount,proto3" json:"token_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AICallResponse) Reset() {
	*x = AICallResponse{}
	mi := &file_proto_ai_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AICallResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AICallResponse) ProtoMessage() {}

func (x *AICallResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ai_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AICallResponse.ProtoReflect.Descriptor instead.
func (*AICallResponse) Descriptor() ([]byte, []int) {
	return file_proto_ai_service_proto_rawDescGZIP(), []int{1}
}

func (x *AICallResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *AICallResponse) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *AICallResponse) GetTokenCount() int32 {
	if x != nil {
		return x.TokenCount
	}
	return 0
}

var File_proto_ai_service_proto protoreflect.FileDescriptor

const file_proto_ai_service_proto_rawDesc = "" +
	"\n" +
	"\x16proto/ai_service.proto\x12\x05proto\"~\n" +
	"\rAICallRequest\x12\x16\n" +
	"\x06prompt\x18\x01 \x01(\tR\x06prompt\x12\x14\n" +
	"\x05model\x18\x02 \x01(\tR\x05model\x12\x1d\n" +
	"\n" +
	"max_tokens\x18\x03 \x01(\x05R\tmaxTokens\x12 \n" +
	"\vtemperature\x18\x04 \x01(\x02R\vtemperature\"_\n" +
	"\x0eAICallResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\tR\x06result\x12\x14\n" +
	"\x05model\x18\x02 \x01(\tR\x05model\x12\x1f\n" +
	"\vtoken_count\x18\x03 \x01(\x05R\n" +
	"tokenCount2B\n" +
	"\tAIService\x125\n" +
	"\x06CallAI\x12\x14.proto.AICallRequest\x1a\x15.proto.AICallResponseB\fZ\a./proto\x90\x01\x01b\x06proto3"

var (
	file_proto_ai_service_proto_rawDescOnce sync.Once
	file_proto_ai_service_proto_rawDescData []byte
)

func file_proto_ai_service_proto_rawDescGZIP() []byte {
	file_proto_ai_service_proto_rawDescOnce.Do(func() {
		file_proto_ai_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_ai_service_proto_rawDesc), len(file_proto_ai_service_proto_rawDesc)))
	})
	return file_proto_ai_service_proto_rawDescData
}

var file_proto_ai_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_ai_service_proto_goTypes = []any{
	(*AICallRequest)(nil),  // 0: proto.AICallRequest
	(*AICallResponse)(nil), // 1: proto.AICallResponse
}
var file_proto_ai_service_proto_depIdxs = []int32{
	0, // 0: proto.AIService.CallAI:input_type -> proto.AICallRequest
	1, // 1: proto.AIService.CallAI:output_type -> proto.AICallResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_ai_service_proto_init() }
func file_proto_ai_service_proto_init() {
	if File_proto_ai_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_ai_service_proto_rawDesc), len(file_proto_ai_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_ai_service_proto_goTypes,
		DependencyIndexes: file_proto_ai_service_proto_depIdxs,
		MessageInfos:      file_proto_ai_service_proto_msgTypes,
	}.Build()
	File_proto_ai_service_proto = out.File
	file_proto_ai_service_proto_goTypes = nil
	file_proto_ai_service_proto_depIdxs = nil
}
