# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/ai_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'proto/ai_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16proto/ai_service.proto\x12\x05proto\"W\n\rAICallRequest\x12\x0e\n\x06prompt\x18\x01 \x01(\t\x12\r\n\x05model\x18\x02 \x01(\t\x12\x12\n\nmax_tokens\x18\x03 \x01(\x05\x12\x13\n\x0btemperature\x18\x04 \x01(\x02\"D\n\x0e\x41ICallResponse\x12\x0e\n\x06result\x18\x01 \x01(\t\x12\r\n\x05model\x18\x02 \x01(\t\x12\x13\n\x0btoken_count\x18\x03 \x01(\x05\x32\x42\n\tAIService\x12\x35\n\x06\x43\x61llAI\x12\x14.proto.AICallRequest\x1a\x15.proto.AICallResponseB\x0cZ\x07./proto\x90\x01\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.ai_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\007./proto\220\001\001'
  _globals['_AICALLREQUEST']._serialized_start=33
  _globals['_AICALLREQUEST']._serialized_end=120
  _globals['_AICALLRESPONSE']._serialized_start=122
  _globals['_AICALLRESPONSE']._serialized_end=190
  _globals['_AISERVICE']._serialized_start=192
  _globals['_AISERVICE']._serialized_end=258
_builder.BuildServices(DESCRIPTOR, 'proto.ai_service_pb2', _globals)
# @@protoc_insertion_point(module_scope)
